/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package kampus_merdeka;

import java.awt.HeadlessException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Julian Marcell
 */
public class Form_eksekusi extends javax.swing.JFrame {
    
    /**
     * Creates new form Form_eksekusi
     */
    public Form_eksekusi() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbPilih = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        btnAksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dibuat Oleh : Julian Marcell Santana");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40))
        );

        cbPilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu", "Nomor 1", "Nomor 2", "Nomor 3", "Nomor 4", "Nomor 5" }));
        cbPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPilihActionPerformed(evt);
            }
        });

        jLabel2.setText("Silahkan Pilih :");

        btnAksi.setBackground(new java.awt.Color(0, 0, 102));
        btnAksi.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnAksi.setForeground(new java.awt.Color(255, 255, 255));
        btnAksi.setText("Action");
        btnAksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtInput)
                            .addComponent(cbPilih, 0, 129, Short.MAX_VALUE))
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAksi)
                        .addGap(133, 133, 133))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPilih, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAksi)
                .addGap(0, 116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cbPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPilihActionPerformed
    
    private void btnAksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAksiActionPerformed
        // TODO add your handling code here:
        switch(cbPilih.getSelectedIndex()){
            case 1:
                try {
                    int input = Integer.parseInt(txtInput.getText());
                    if (input%5==0) {
                        JOptionPane.showMessageDialog(this, "World");
                    }else if (input%3==0) {
                        JOptionPane.showMessageDialog(this, "Hello");
                    }else{
                        JOptionPane.showMessageDialog(this, "Hello World");
                    }
                } catch (HeadlessException | NumberFormatException e) {
                    e.getMessage();
                }
                break;
            case 2:
                try {
                    
                    String email = txtInput.getText();
                    int panjang = email.length();
                    
                        if(panjang >= 20){
                            JOptionPane.showMessageDialog(this, "Email tidak boleh lebih dari 20");
                        }else if (email.trim().equals("")) {
                            JOptionPane.showMessageDialog(this, "Email tidak boleh kosong");
                        }else if (!email.contains("@") && !email.contains(".")) {
                            JOptionPane.showMessageDialog(this, "Email harus menggunakan (@) dan (.)");
                        }else if (!email.contains(".co.id") && !email.contains(".id")) {
                            JOptionPane.showMessageDialog(this, "Domain Tersedia Hanya (.co.id & .id)");
                        }else{
                            JOptionPane.showMessageDialog(this, "Email "+email+" berhasil masuk");
                        }
                    
                } catch (HeadlessException e) {
                    e.getMessage();
                }
                break;
            case 3:
                try {
                    String waktu = txtInput.getText();
                    if (waktu.contains("PM") || waktu.contains("pm")) {
                        JOptionPane.showMessageDialog(null,"Waktu PM "+waktu.replace("PM","  "));
                    }else if (waktu.contains("AM") || waktu.contains("am")) {
                        JOptionPane.showMessageDialog(null,"Waktu AM "+waktu.replace("12", "00"));
                    }else if (waktu.contains("AM") || waktu.contains("am")) {
                        JOptionPane.showMessageDialog(null,"Waktu AM "+waktu.replace("13", "01"));
                    }else if (waktu.contains("AM") || waktu.contains("am")) {
                        JOptionPane.showMessageDialog(null,"Waktu AM "+waktu.replace("14", "02"));
                    }else if (waktu.contains("AM") || waktu.contains("am")) {
                        JOptionPane.showMessageDialog(null,"Waktu AM "+waktu.replace("15", "03"));
                    }else if (waktu.contains("AM") || waktu.contains("am")) {
                        JOptionPane.showMessageDialog(null,"Waktu AM "+waktu.replace("16", "04"));
                    }else if (waktu.contains("AM") || waktu.contains("am")) {
                        JOptionPane.showMessageDialog(null,"Waktu AM "+waktu.replace("17", "05"));
                    }else if (waktu.contains("AM") || waktu.contains("am")) {
                        JOptionPane.showMessageDialog(null,"Waktu AM "+waktu.replace("18", "06"));
                    }else if (waktu.contains("AM") || waktu.contains("am")) {
                        JOptionPane.showMessageDialog(null,"Waktu AM "+waktu.replace("19", "07"));
                    }else if (waktu.contains("AM") || waktu.contains("am")) {
                        JOptionPane.showMessageDialog(null,"Waktu AM "+waktu.replace("20", "08"));
                    }else if (waktu.contains("AM") || waktu.contains("am")) {
                        JOptionPane.showMessageDialog(null,"Waktu AM "+waktu.replace("21", "09"));
                    }else if (waktu.contains("AM") || waktu.contains("am")) {
                        JOptionPane.showMessageDialog(null,"Waktu AM "+waktu.replace("22", "10"));
                    }else if (waktu.contains("AM") || waktu.contains("am")) {
                        JOptionPane.showMessageDialog(null,"Waktu AM "+waktu.replace("23", "11"));
                    }else{
                        JOptionPane.showMessageDialog(null, "No Problem");
                    }
                    
                } catch (HeadlessException e) {
                    e.getMessage();
                }
                break;
            case 4:
                try {
                    String kebalik ="";
                    String input = txtInput.getText();
                    
                    int jml = input.length();
                    int jmlhuruf = jml-1;
                    for (int i = 0; i < jml; i++) {
                        kebalik = kebalik + input.charAt(jmlhuruf);
                        jmlhuruf--;
                    }
                    JOptionPane.showMessageDialog(null, "Dari "+input+" menjadi "+kebalik);
                } catch (HeadlessException e) {
                    e.getMessage();
                }
                break;
            case 5:
                try {
                    String input = txtInput.getText();
                    
                    JOptionPane.showMessageDialog(null, "Hello Nama saya adalah "+input);
                } catch (HeadlessException e) {
                    e.getMessage();
                }
                break;
                
            default:
        }
    }//GEN-LAST:event_btnAksiActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_eksekusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_eksekusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_eksekusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_eksekusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_eksekusi().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAksi;
    private javax.swing.JComboBox<String> cbPilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
